### ISSUE TITLE
Fails when there is an escape character in a commit message

### ISSUE THREAD

**Issue by bortzmeyer** [purcell/darcs-to-git#27]
Indeed, it is a bad idea to have such characters in the commit messages but darcs chandles them:

```
/usr/lib/ruby/gems/3.2.0/gems/rexml-3.2.5/lib/rexml/parsers/treeparser.rb:96:in `rescue in parse': #<RuntimeError: Illegal character "\b" in raw string "Toujours en DISCUSS a l&apos;IEG\bSG"> (REXML::ParseException)
/usr/lib/ruby/gems/3.2.0/gems/rexml-3.2.5/lib/rexml/text.rb:140:in `block in check'
/usr/lib/ruby/gems/3.2.0/gems/rexml-3.2.5/lib/rexml/text.rb:136:in `each'
/usr/lib/ruby/gems/3.2.0/gems/rexml-3.2.5/lib/rexml/text.rb:136:in `check'
/usr/lib/ruby/gems/3.2.0/gems/rexml-3.2.5/lib/rexml/text.rb:122:in `initialize'
/usr/lib/ruby/gems/3.2.0/gems/rexml-3.2.5/lib/rexml/parsers/treeparser.rb:47:in `new'
/usr/lib/ruby/gems/3.2.0/gems/rexml-3.2.5/lib/rexml/parsers/treeparser.rb:47:in `parse'
/usr/lib/ruby/gems/3.2.0/gems/rexml-3.2.5/lib/rexml/document.rb:448:in `build'
/usr/lib/ruby/gems/3.2.0/gems/rexml-3.2.5/lib/rexml/document.rb:101:in `initialize'
../darcs-to-git/darcs-to-git:326:in `new'
../darcs-to-git/darcs-to-git:326:in `read_from_repo'
../darcs-to-git/darcs-to-git:564:in `<main>'
...
Illegal character "\b" in raw string "Toujours en DISCUSS a l&apos;IEG\bSG"
Line: 6126
Position: 465373
```

**Comment by purcell** [comment]
The problem suggested by this stacktrace is that Darcs is outputting characters that are illegal in XML — we're using [this darcs command](https://github.com/purcell/darcs-to-git/blob/master/darcs-to-git#L326-L328) to export changes.

**Comment by bortzmeyer** [comment]
> Darcs is outputting characters that are illegal in XML 

You mean darcs should escape these characters, and I should report this bug against darcs ?

**Comment by purcell** [comment]
Yes. In XML 1.0 these characters were completely illegal, and in XML 1.1 they must be escaped. Here they are apparently unescaped, and are therefore invalid for both versions of the XML format.

**Comment by bortzmeyer** [comment]
> Yes. In XML 1.0 these characters were completely illegal, and in XML 1.1 they must be escaped. 

https://bugs.darcs.net/issue2732
